export const registerContentDe = {
  languageLabel: "Deutsch",
  footerPrivacy: "Datenschutz",
  footerImprint: "Impressum",
  footerTerms: "AGB",
  footerFaq: "FAQ",
  step1Title: "Starte dein Abenteuer\nmit WellFit!",
  step1Subtitle: "Registriere dich kostenlos und werde Teil unserer Community.",
  firstName: "Vorname",
  lastName: "Nachname",
  email: "E-Mail-Adresse eingeben",
  password: "Passwort erstellen",
  confirmPassword: "Passwort bestätigen",
  acceptPrefix: "Ich akzeptiere die ",
  privacyPolicy: "Datenschutzbestimmungen",
  and: " und ",
  terms: "AGB",
  registerNow: "Jetzt registrieren",
  alreadyAccount: "Bereits ein Konto?",
  login: "Anmelden",
  benefit1Title: "Bewege dich im Alltag",
  benefit1Text: "Deine Schritte, Workouts & Aktivitäten zählen.",
  benefit2Title: "Sammle Punkte",
  benefit2Text: "Verdiene Punkte und Belohnungen für jede Bewegung.",
  benefit3Title: "Level dein Tamagotchi auf",
  benefit3Text: "Spiele, sammle Belohnungen und steigere deinen Fortschritt.",
  biometricsPhase: "PHASE 02: BIOMETRIE",
  setupTitle: "KI-CHARAKTER SETUP",
  birthdate: "Geburtsdatum",
  gender: "Geschlecht",
  male: "Männlich",
  female: "Weiblich",
  diverse: "Divers",
  size: "Größe",
  weight: "Gewicht",
  bodyType: "Körperbau",
  slim: "Schlank",
  athletic: "Athletisch",
  strong: "Kraftvoll",
  targetWeight: "Zielgewicht anstreben",
  fitnessLevel: "Fitnesslevel",
  beginner: "Anfänger",
  medium: "Fortgeschritten",
  pro: "Profi",
  medication: "Medikamenteneinnahme?",
  yes: "Ja",
  no: "Nein",
  limitations: "Einschränkungen",
  sleepProfile: "Schlafprofil",
  nutrition: "Ernährung",
  hydration: "Hydrierung",
  drinkReminder: "Soll ich dich erinnern, etwas zu trinken?",
  drinkAmount: "Wie viel willst du am Tag trinken?",
  stressLevel: "Stresslevel",
  movementNature: "Bewegung in der Natur",
  scan: "Scan",
  nutritionAll: "Alles",
  nutritionVeggie: "Veggie",
  nutritionVegan: "Vegan",
  less6: "< 6h",
  between6and8: "6-8h",
  more8: "> 8h",
  sleepGood: "Gut",
  sleepMid: "Mittel",
  sleepBad: "Schlecht",
  move15: "15 - 30 Min.",
  move60: "~ 1 Stunde",
  moveMore: "> 1 Std.",
  next: "Weiter",
  psychPhase: "PHASE 03: PSYCHOGRAPHIE",
  tuningTitle: "BUDDY-TUNING",
  activeNow: "Wie aktiv bist du aktuell?",
  almostInactive: "Kaum aktiv",
  sometimes: "Gehe gelegentlich",
  regular: "Trainiere regelmäßig",
  veryActive: "Treibe ausreichend Sport",
  interests: "Was interessiert dich am meisten?",
  communityMode: "Community-Modus",
  publicBoard: "Öffentliches Leaderboard",
  privateSquads: "Nur private Squads",
  soloMode: "Einzelgänger-Modus",
  trainingTime: "Beste Trainingszeit",
  morning: "Morgens (Early Bird)",
  noon: "Mittags",
  evening: "Abends (Night Owl)",
  goals: "Was sind deine Ziele?",
  loseWeight: "Abnehmen",
  improveFitness: "Fitness steigern",
  stayHealthy: "Gesund bleiben",
  adventure: "Abenteuer erleben",
  activities: "Bevorzugte Aktivität",
  walking: "Gehen",
  running: "Laufen",
  cycling: "Radfahren",
  dancing: "Tanzen",
  workout: "Workout",
  relax: "Entspannung",
  biometricsEnable: "Biometrie jetzt aktivieren",
  activateLater: "Später aktivieren",
  createAvatar: "KI Analyse starten",
  awakenTitle: "Dein Avatar wird erschaffen",
  awakenText: "Die WellFit KI analysiert jetzt deine Angaben, erschafft deinen Buddy und erweckt ihn zum Leben.",
  awakenSub1: "Biometrie wird synchronisiert",
  awakenSub2: "Persönlichkeit wird kalibriert",
  awakenSub3: "Avatar-Kern wird aktiviert",
  awakenDone: "Avatar erfolgreich erweckt. Weiterleitung zum Dashboard...",
} as const;
