export const registerContentEn = {
  languageLabel: "English",
  footerPrivacy: "Privacy",
  footerImprint: "Imprint",
  footerTerms: "Terms",
  footerFaq: "FAQ",
  step1Title: "Start your adventure\nwith WellFit!",
  step1Subtitle: "Register for free and become part of our community.",
  firstName: "First name",
  lastName: "Last name",
  email: "Enter your email address",
  password: "Create password",
  confirmPassword: "Confirm password",
  acceptPrefix: "I accept the ",
  privacyPolicy: "privacy policy",
  and: " and ",
  terms: "terms",
  registerNow: "Register now",
  alreadyAccount: "Already have an account?",
  login: "Sign in",
  benefit1Title: "Stay active every day",
  benefit1Text: "Your steps, workouts & activities count.",
  benefit2Title: "Collect points",
  benefit2Text: "Earn digital rewards for every move.",
  benefit3Title: "Level up your Tamagotchi",
  benefit3Text: "Play, collect rewards and improve your progress.",
  biometricsPhase: "PHASE 02: BIOMETRICS",
  setupTitle: "AI CHARACTER SETUP",
  birthdate: "Date of birth",
  gender: "Gender",
  male: "Male",
  female: "Female",
  diverse: "Diverse",
  size: "Height",
  weight: "Weight",
  bodyType: "Body type",
  slim: "Slim",
  athletic: "Athletic",
  strong: "Strong",
  targetWeight: "Aim for target weight",
  fitnessLevel: "Fitness level",
  beginner: "Beginner",
  medium: "Advanced",
  pro: "Pro",
  medication: "Taking medication?",
  yes: "Yes",
  no: "No",
  limitations: "Restrictions",
  sleepProfile: "Sleep profile",
  nutrition: "Nutrition",
  hydration: "Hydration",
  drinkReminder: "Should I remind you to drink?",
  drinkAmount: "How much do you want to drink per day?",
  stressLevel: "Stress level",
  movementNature: "Movement in nature",
  scan: "Scan",
  nutritionAll: "Everything",
  nutritionVeggie: "Veggie",
  nutritionVegan: "Vegan",
  less6: "< 6h",
  between6and8: "6-8h",
  more8: "> 8h",
  sleepGood: "Good",
  sleepMid: "Average",
  sleepBad: "Poor",
  move15: "15 - 30 min.",
  move60: "~ 1 hour",
  moveMore: "> 1 hour",
  next: "Next",
  psychPhase: "PHASE 03: PSYCHOGRAPHY",
  tuningTitle: "BUDDY TUNING",
  activeNow: "How active are you right now?",
  almostInactive: "Barely active",
  sometimes: "Sometimes active",
  regular: "Train regularly",
  veryActive: "Very active",
  interests: "What interests you most?",
  communityMode: "Community mode",
  publicBoard: "Public leaderboard",
  privateSquads: "Private squads only",
  soloMode: "Solo mode",
  trainingTime: "Best training time",
  morning: "Morning (Early Bird)",
  noon: "Noon",
  evening: "Evening (Night Owl)",
  goals: "What are your goals?",
  loseWeight: "Lose weight",
  improveFitness: "Improve fitness",
  stayHealthy: "Stay healthy",
  adventure: "Live adventure",
  activities: "Preferred activity",
  walking: "Walking",
  running: "Running",
  cycling: "Cycling",
  dancing: "Dancing",
  workout: "Workout",
  relax: "Relaxation",
  biometricsEnable: "Enable biometrics now",
  activateLater: "Activate later",
  createAvatar: "Start AI analysis",
  awakenTitle: "Your avatar is being created",
  awakenText: "The WellFit AI is now analyzing your data, creating your buddy and bringing it to life.",
  awakenSub1: "Synchronizing biometrics",
  awakenSub2: "Calibrating personality",
  awakenSub3: "Activating avatar core",
  awakenDone: "Avatar successfully awakened. Redirecting to dashboard...",
} as const;
