#!/usr/bin/env python3
"""Generate a compact Project Memory status report.

This is intentionally dependency-free so it can run in GitHub Actions and locally.
"""
from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MEM = ROOT / "project-memory"
STATUS_FILE = MEM / "PROJECT_STATUS.md"

STATUS_WORDS = [
    "TODO",
    "IN_PROGRESS",
    "BLOCKED",
    "PARTIAL",
    "IMPLEMENTED",
    "IMPLEMENTED_NOT_VERIFIED",
    "VERIFIED",
    "VERIFIED_NOT_ACCEPTED",
    "ACCEPTED",
    "PRODUCTION_CONFIRMED",
    "DONE",
    "REJECTED",
    "SUPERSEDED",
    "DEFERRED",
]


def read(name: str) -> str:
    path = MEM / name
    return path.read_text(encoding="utf-8") if path.exists() else ""


def count_status(text: str) -> dict[str, int]:
    counts = {key: 0 for key in STATUS_WORDS}
    for key in STATUS_WORDS:
        counts[key] = len(re.findall(rf"\bStatus:\s*{re.escape(key)}\b", text))
    return {k: v for k, v in counts.items() if v}


def headings(text: str, limit: int = 12) -> list[str]:
    rows = []
    for line in text.splitlines():
        if line.startswith("## ") and not line.startswith("## Status"):
            rows.append(line[3:].strip())
    return rows[:limit]


def main() -> None:
    task = read("TASK_LEDGER.md")
    changes = read("CHANGE_REQUESTS.md")
    loops = read("OPEN_LOOPS.md")
    deps = read("DEPENDENCIES.md")
    evidence = read("EVIDENCE.md")
    handoff = read("SESSION_HANDOFF.md")

    lines = [
        "# Project Status",
        "",
        "Generated by `scripts/project_memory_status.py`.",
        "",
        "## Status counts",
        "",
    ]
    for source_name, text in [
        ("TASK_LEDGER.md", task),
        ("CHANGE_REQUESTS.md", changes),
        ("OPEN_LOOPS.md", loops),
        ("DEPENDENCIES.md", deps),
        ("EVIDENCE.md", evidence),
    ]:
        counts = count_status(text)
        lines.append(f"### {source_name}")
        if counts:
            for key, value in counts.items():
                lines.append(f"- {key}: {value}")
        else:
            lines.append("- No explicit status markers found.")
        lines.append("")

    lines += ["## Open loops", ""]
    for item in headings(loops):
        lines.append(f"- {item}")
    if not headings(loops):
        lines.append("- None listed.")

    lines += ["", "## Dependencies", ""]
    for item in headings(deps):
        lines.append(f"- {item}")
    if not headings(deps):
        lines.append("- None listed.")

    lines += ["", "## Latest handoff", ""]
    snippet = "\n".join(handoff.splitlines()[:40]).strip()
    lines.append(snippet if snippet else "No handoff recorded.")
    lines.append("")

    STATUS_FILE.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
